- name: question2-2
  hosts: host2
  tasks:
    - shell: /usr/bin/ls
      register: result
      ignore_errors: true
    - debug:
        msg: "It changed"
      when: result is changed
      register: result2
    - debug:
        msg: "It ok"
      when: result is succeeded
    - debug:
        msg: "Result2 is ok"
      when: result2 is succeeded

    