- name: template module test
  hosts: all
  tasks:
    - name: copy to template file
      copy:
        src: hosts.j2
        dest: /tmp
    - name: template module using
      template:
        src: hosts.j2
        dest: /home/vagrant/temp.txt

