- name: test async
  hosts: all
  tasks:
    - name: running time 180
      command: sleep 60
      register: result
      async: 80
      poll: 20
    - name: task2
      debug: 
        msg: hello
    - name: task3
      debug: 
        msg: good
    - name: task4
      debug: 
        msg: bye
    - name: check first task
      async_status:
        jid: result['ansible_job_id']
      register: job_result
      until: job_result