- name: test error host
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: task1 is ok
      command: ls /tmp
    - name: task2 is error
      command: ls /error
    - name:
      command: ls /tmp