---
- name: create hosts
  hosts: all
  tasks:
    - template:
        src: hosts.j2
        dest: /etc/hosts
    # - debug:
    #     msg: "{{ hostvars['host1']['ansible_eth1']['ipv4']['address'] }}"